# Configuración base del microservicio
server.port=8099
spring.application.name=biblioteca-service

# Interruptor central: Activamos el perfil de pruebas unitarias por defecto para JUnit
spring.profiles.active=test