# Base de datos aislada exclusivamente para pruebas unitarias de la biblioteca
spring.datasource.url=jdbc:postgresql://localhost:5432/stimy_biblioteca_db_test
spring.datasource.username=postgres
spring.datasource.password=tu_contrasena_postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# create-drop: Borra la base de datos de test por completo y la vuelve a crear vacía en cada test
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Evitamos cargar scripts data.sql externos para simular los datos con Mockito
spring.sql.init.mode=never