# Base de datos local de desarrollo (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/stimy_carrito_db_dev
spring.datasource.username=postgres
spring.datasource.password=tu_contrasena_postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración JPA e Hibernate para desarrollo diario
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Inicialización de scripts sql de prueba
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true