# Configuración base del microservicio Carrito
server.port=8093
spring.application.name=carrito-service

# Perfil activo por defecto (ideal para los tests de JUnit del profesor)
spring.profiles.active=test