# Base de datos aislada para pruebas unitarias de Logros
spring.datasource.url=jdbc:postgresql://localhost:5432/stimy_logro_db_test
spring.datasource.username=postgres
spring.datasource.password=tu_contrasena_postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# create-drop: Limpia la BD al finalizar los tests
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.sql.init.mode=never