# Base de datos exclusiva para pruebas unitarias de Deseos
spring.datasource.url=jdbc:postgresql://localhost:5432/stimy_deseo_db_test
spring.datasource.username=postgres
spring.datasource.password=tu_contrasena_postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# create-drop: Estructura la BD al iniciar el test y la borra por completo al terminar
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Desactivar la carga de scripts SQL en modo test
spring.sql.init.mode=never