# Base de datos local para desarrollo diario en PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/stimy_biblioteca_db_dev
spring.datasource.username=postgres
spring.datasource.password=tu_contrasena_postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración JPA e Hibernate para desarrollo
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Inicialización de scripts (data.sql)
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true