server.port=8080
spring.application.name=api-gateway

# --- TABLA DE ENRUTAMIENTO DE MICROSERVICIOS ---

# 1. Enrutamiento hacia usuario-service (8081)
spring.cloud.gateway.routes[0].id=usuario-route
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/usuarios/**

# 2. Enrutamiento hacia videojuego-service (8082)
spring.cloud.gateway.routes[1].id=videojuego-route
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/videojuegos/**

# 3. Enrutamiento hacia carrito-service (8083)
spring.cloud.gateway.routes[2].id=carrito-route
spring.cloud.gateway.routes[2].uri=http://localhost:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/carritos/**

# 4. Enrutamiento hacia deseo-service (8084)
spring.cloud.gateway.routes[3].id=deseo-route
spring.cloud.gateway.routes[3].uri=http://localhost:8084
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/deseos/**

# 5. Enrutamiento hacia logro-service (8085)
spring.cloud.gateway.routes[4].id=logro-route
spring.cloud.gateway.routes[4].uri=http://localhost:8085
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/logros/**

# 6. Enrutamiento hacia resenia-service (8086)
spring.cloud.gateway.routes[5].id=resenia-route
spring.cloud.gateway.routes[5].uri=http://localhost:8086
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/resenias/**

# 7. Enrutamiento hacia soporte-service (8087)
spring.cloud.gateway.routes[6].id=soporte-route
spring.cloud.gateway.routes[6].uri=http://localhost:8087
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/soporte/**

# 8. Enrutamiento hacia pago-service (8088)
spring.cloud.gateway.routes[7].id=pago-route
spring.cloud.gateway.routes[7].uri=http://localhost:8088
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/pagos/**

# 9. Enrutamiento hacia biblioteca-service (8089)
spring.cloud.gateway.routes[8].id=biblioteca-route
spring.cloud.gateway.routes[8].uri=http://localhost:8089
spring.cloud.gateway.routes[8].predicates[0]=Path=/api/bibliotecas/**