server.port=8081
spring.application.name=api-gateway

eureka.client.healthcheck.enabled=false
eureka.instance.status-page-url-path=/actuator/info
eureka.instance.health-check-url-path=/actuator/health

# --- TABLA DE ENRUTAMIENTO DINÁMICO (CON EUREKA) ---

# 1. Enrutamiento hacia usuario-service
spring.cloud.gateway.routes[0].id=usuario-route
spring.cloud.gateway.routes[0].uri=lb://usuario-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/usuarios/**

# 2. Enrutamiento hacia videojuego-service
spring.cloud.gateway.routes[1].id=videojuego-route
spring.cloud.gateway.routes[1].uri=lb://videojuego-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/videojuegos/**

# 3. Enrutamiento hacia carrito-service
spring.cloud.gateway.routes[2].id=carrito-route
spring.cloud.gateway.routes[2].uri=lb://carrito-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/carritos/**

# 4. Enrutamiento hacia deseo-service
spring.cloud.gateway.routes[3].id=deseo-route
spring.cloud.gateway.routes[3].uri=lb://deseo-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/deseos/**

# 5. Enrutamiento hacia logro-service
spring.cloud.gateway.routes[4].id=logro-route
spring.cloud.gateway.routes[4].uri=lb://logro-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/logros/**

# 6. Enrutamiento hacia resenia-service
spring.cloud.gateway.routes[5].id=resenia-route
spring.cloud.gateway.routes[5].uri=lb://resenia-service
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/resenias/**

# 7. Enrutamiento hacia soporte-service
spring.cloud.gateway.routes[6].id=soporte-route
spring.cloud.gateway.routes[6].uri=lb://soporte-service
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/soporte/**

# 8. Enrutamiento hacia pago-service
spring.cloud.gateway.routes[7].id=pago-route
spring.cloud.gateway.routes[7].uri=lb://pago-service
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/pagos/**

# 9. Enrutamiento hacia biblioteca-service
spring.cloud.gateway.routes[8].id=biblioteca-route
spring.cloud.gateway.routes[8].uri=lb://biblioteca-service
spring.cloud.gateway.routes[8].predicates[0]=Path=/api/bibliotecas/**


# --- CONEXIÓN DE API GATEWAY A EUREKA SERVER ---
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/


# --- CONFIGURACIÓN DE SWAGGER CENTRALIZADO ---
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
#springdoc.swagger-ui.path=/doc/swagger-ui.html
springdoc.enable-native-support=true
springdoc.swagger-ui.urls-by-name-transform-strategy=



# Obliga a Swagger a usar el puerto y host del Gateway para todas las peticiones (Server URL)
springdoc.swagger-ui.supported-submit-methods=["get", "post", "put", "delete", "patch"]
#springdoc.swagger-ui.configs-override.server-url=/


